spring:
  application:
    name: "User Management"

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:postgresql://localhost:17001/user-management
#    username: testuser_readwrite
#    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Optional: for troubleshooting
  sql:
    init:
      mode: always

# Server port (optional)
server:
  port: 8085

# langraph agent url
external:
  agent:
    url: http://host.docker.internal:8000

