server:
  port: 8085
spring:
  application:
    name: "User Management"

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:postgresql://localhost:17001/user-management
#    username: testuser_readwrite
#    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
jwt:
  issuer: user-management-api

fastapi:
  base-url: ${FASTAPI_BASE_URL:http://host.docker.internal:8000}  # default for docker-compose
  secret-key: ${FASTAPI_SECRET_KEY:spring-secret-key}
