services:
  - type: web
    name: spring-boot-backend
    env: docker
    repo: https://github.com/deepgahlot11/company_research_platform
    dockerfilePath: ./management/Dockerfile
    dockerContext: ./management
    buildCommand: ./gradlew build
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: user_management_db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: user_management_db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: user_management_db
          property: password
    plan: free
    autoDeploy: true

  - type: web
    name: react-frontend
    env: docker
    repo: https://github.com/deepgahlot11/company_research_platform
    dockerfilePath: ./insight-compass-researcher-app/Dockerfile
    dockerContext: ./insight-compass-researcher-app
    buildCommand: npm install && npm run build
    plan: free
    autoDeploy: true

  - type: web
    name: langgraph-agent
    env: docker
    repo: https://github.com/deepgahlot11/company_research_platform
    dockerfilePath: ./company-researcher/Dockerfile
    dockerContext: ./company-researcher
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyDe0WzZzZLvTALYe9Otpur8hg9VVJ5b_B4
      - key: TAVILY_API_KEY
        value: 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
      - key: SECRET_KEY
        value: spring-secret-key
    plan: free
    autoDeploy: true

databases:
  - name: user_management_db
    databaseName: user_management
    user: testuser_readwrite
    plan: free
